spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: CursoJAVA2021
    url: jdbc:mysql://localhost:3306/tiendavirtual?serverTimezone=UTC
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 10000
eureka:
  instance:
    instance-id: instanciaB
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
